config/routes.rb
Rails.application.routes.draw do

   root 'individials#index'

end

app/models/individial.rb
class Individial < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/individials_controller.rb
class IndividialsController < ApplicationController
  before_action :set_individial, only: [:show, :edit, :update, :destroy]

  # GET /individials
  # GET /individials.json
  def index
    @individials = Individial.all
  end

  # GET /individials/1
  # GET /individials/1.json
  def show
  end

  # GET /individials/new
  def new
    @individial = Individial.new
  end

  # GET /individials/1/edit
  def edit
  end

  # POST /individials
  # POST /individials.json
  def create
    @individial = Individial.new(individial_params)

    respond_to do |format|
      if @individial.save
        format.html { redirect_to @individial, notice: 'Individial was successfully created.' }
        format.json { render :show, status: :created, location: @individial }
      else
        format.html { render :new }
        format.json { render json: @individial.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /individials/1
  # PATCH/PUT /individials/1.json
  def update
    respond_to do |format|
      if @individial.update(individial_params)
        format.html { redirect_to @individial, notice: 'Individial was successfully updated.' }
        format.json { render :show, status: :ok, location: @individial }
      else
        format.html { render :edit }
        format.json { render json: @individial.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /individials/1
  # DELETE /individials/1.json
  def destroy
    @individial.destroy
    respond_to do |format|
      format.html { redirect_to individials_url, notice: 'Individial was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_individial
      @individial = Individial.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def individial_params
      params.require(:individial).permit(:name, :weight, :height, :color, :education, :nationality)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/individials/_form.html.erb
<%= form_for(@individial) do |f| %>
  <% if @individial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@individial.errors.count, "error") %> prohibited this individial from being saved:</h2>

      <ul>
      <% @individial.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :weight %><br>
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :education %><br>
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :nationality %><br>
    <%= f.text_field :nationality %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/individials/edit.html.erb
<h1>Editing Individial</h1>

<%= render 'form' %>

<%= link_to 'Show', @individial %> |
<%= link_to 'Back', individials_path %>

app/views/individials/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Individials</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Weight</th>
      <th>Height</th>
      <th>Color</th>
      <th>Education</th>
      <th>Nationality</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @individials.each do |individials| %>
      <tr>
        <td><%= individials.name %></td>
        <td><%= individials.weight %></td>
        <td><%= individials.height %></td>
        <td><%= individials.color %></td>
        <td><%= individials.education %></td>
        <td><%= individials.nationality %></td>
        <td><%= link_to 'Show', individials %></td>
        <td><%= link_to 'Edit', edit_individials_path(individials) %></td>
        <td><%= link_to 'Destroy', individials, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Individial', new_individials_path %>

app/views/individials/new.html.erb
<h1>New Individial</h1>

<%= render 'form' %>

<%= link_to 'Back', individials_path %>

app/views/individials/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @individial.name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @individial.weight %>
</p>

<p>
  <strong>Height:</strong>
  <%= @individial.height %>
</p>

<p>
  <strong>Color:</strong>
  <%= @individial.color %>
</p>

<p>
  <strong>Education:</strong>
  <%= @individial.education %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @individial.nationality %>
</p>

<%= link_to 'Edit', edit_individial_path(@individial) %> |
<%= link_to 'Back', individials_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assignew2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>